#!/usr/bin/env ruby

require 'optparse'
require_relative 'main'

usage = "Usage: rbhead [options] FILENAME"
options = {}
OptionParser.new do |parser|
  parser.banner = usage

  parser.on("-n LINES", Integer, "Specify the number of lines to output") do |lines|
    options[:n] = lines
  end

  parser.on("-c BYTES", Integer, "Specify the number of bytes to output") do |bytes|
    options[:c] = bytes
  end

  parser.on("-h", "--help", "Prints this help") do
    puts parser
    exit
  end
end.parse!

if ARGV[0].nil? || ARGV[0].empty?
  puts 'missing file_name'
  puts usage
  exit
end


def run_script(file_path, options, multi_files)
  rbhead = nil
  if options.key?(:n)
    rbhead = RbHead.new(file_path, n: options[:n])
  elsif options.key?(:c)
    rbhead = RbHead.new(file_path, c: options[:c])
  else
    rbhead = RbHead.new(file_path)
  end

  if multi_files == true
    puts "==> #{File.basename(file_path)} <=="
  end

  puts rbhead.run
end

multi_files = ARGV.length > 1? true: false
ARGV.each do |file_path|
  run_script(file_path, options, multi_files)
  puts
end
